---
title: "Computing extremes of observed continuous variables"
author: "Katherine Goode"
date: 'Last Updated: `r format(Sys.time(), "%B %d, %Y")`'
output:
  pdf_document:
    highlight: haddock
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(dplyr)
library(tidyr)
```

```{r}
eggdata <- read.csv("../data/eggdata_for_app.csv")
```

```{r}
unique(eggdata$Month)
sort(unique(eggdata$Julian_Day))
```


```{r}
unique(eggdata$Deflated)
unique(eggdata$Pigment)
unique(eggdata$Egg_Stage)
unique(eggdata$Compact_Diffuse)
unique(eggdata$Sticky_Debris)
```


```{r}
eggdata %>%
  select(
    Temperature,
    Conductivity,
    Larval_Length,
    Membrane_Ave,
    Membrane_SD,
    Membrane_CV,
    Yolk_to_Membrane_Ratio,
    Yolk_Ave,
    Yolk_SD,
    Yolk_CV
  ) %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = everything()
  ) %>%
  group_by(variable) %>%
  summarise(
    min = round(min(value), 3),
    max = round(max(value), 3)
  )
```

