---
title: "Computing values for WhoseEgg"
author: "Katherine Goode"
date: 'Last Updated: `r format(Sys.time(), "%B %d, %Y")`'
output: rmarkdown::github_document
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
# Load packages
library(dplyr)
library(tidyr)
```

```{r}
# Load egg data
eggdata <- read.csv("../data/eggdata_for_app.csv")
```

## Species table

```{r}
# Make table
eggdata %>% 
  count(Family_ACGC, Genus_ACGC, Common_Name_ACGC) %>% 
  rename(
    "Family" = "Family_ACGC",
    "Genus" = "Genus_ACGC",
    "Common Name" = "Common_Name_ACGC",
    "Number of Eggs in Training Data" = "n"
  ) %>%
  knitr::kable(align = "lllc") %>%
  kableExtra::column_spec(
    column = 1:4,
    width = "3cm"
  ) %>%
  kableExtra::collapse_rows(
    columns = 1:3,
    valign = "top"
  )
```

## Computing variable levels and extreme values

Date variables: 

```{r}
unique(eggdata$Month)
sort(unique(eggdata$Julian_Day))
```

Categorical variables:

```{r}
unique(eggdata$Deflated)
unique(eggdata$Pigment)
unique(eggdata$Egg_Stage)
unique(eggdata$Compact_Diffuse)
unique(eggdata$Sticky_Debris)
```

Continuous variables: 

```{r}
eggdata %>%
  select(
    Temperature,
    Conductivity,
    Larval_Length,
    Membrane_Ave,
    Membrane_SD,
    Membrane_CV,
    Yolk_to_Membrane_Ratio,
    Yolk_Ave,
    Yolk_SD,
    Yolk_CV
  ) %>%
  pivot_longer(
    names_to = "variable",
    values_to = "value",
    cols = everything()
  ) %>%
  group_by(variable) %>%
  summarise(
    min = round(min(value), 3),
    max = round(max(value), 3)
  )
```

