---
output:
  html_document:
    theme: flatly
---

This page contains the tools for providing the fish egg characteristics that will be used by the random forests to predict the fish taxonomies. To provide the egg characteristics, follow the instructions in the sidebar panel to the left.

The egg characteristic data must be formatted appropriately to work with WhoseEgg and correctly obtain predictions. Follow the guidelines in the **Spreadsheet Specifications** tabs below. Once the egg characteristic spreadsheet is uploaded, several additional variables will be computed based on the input values to be used by the random forests: `Julian_Day`, `Membrane_SD`, `Membrane_CV`, `Embryo_SD`, `Embryo_CV`, and `Embryo_to_Membrane_Ratio`. The uploaded variables of `Year` and `Day` are only used by WhoseEgg to compute `Julian_Day` and are excluded from the processed data.

Under **Egg Characteristics**, see the 'Input Data' tab to view data in the uploaded spreadsheet and the 'Processed Data' tab for the set of predictor variables to be used by the random forest plus the Egg ID.