---
output:
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
.textbox {
  padding: 1em;
  background: #EBF0F1;
  color: #273E52;
  border-radius: 10px;
}
```


:::: {.textbox data-latex=""}

**Columns in Template**

- Fill in all variables (egg_ID and 13 egg characteristics)

- See the help page for detailed definitions of the egg characteristics (includes example photos)

- There is no maximum to the number of observations that may be included but at least one egg observations is required

**Template Formatting Helpers**

- Select a cell with a variable name to see required formats, units, or accepted levels

- Cells of categorical variables contains drop down options  

- Errors or warnings will appear if a values is not formatted correctly  

**Additional Variables**

- It is okay to include additional variables in the uploaded spreadsheet

- Additional variables will be excluded from the processed data used for prediction but included in final downloadable spreadsheet

::::
